apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: house-train
  annotations:
    scenarios.ai.sap.com/description: "Workflow for training a house price prediction model"
    scenarios.ai.sap.com/name: "House Price Prediction (Training)"
    executables.ai.sap.com/description: "Train a model using a dataset"
    executables.ai.sap.com/name: "house-train"
  labels:
    scenarios.ai.sap.com/id: "house-price-prediction"
    ai.sap.com/version: "1.0.0"
spec:
  imagePullSecrets:
    - name: seifeldinfathi
  entrypoint: main
  templates:
    - name: main
      container:
        image: python:3.8
        command: [python, /app/train.py]
        workingDir: /app
        env:
          - name: DATASET_PATH
            value: "/app/data/house-prices.csv"
          - name: MODEL_PATH
            value: "/app/model"
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "0.5"